### ISSUE TITLE
Pier flickering / bad layer ordering

### ISSUE THREAD

**Issue by matteblair** [tangrams/eraser-map#114]
The `order` set for piers ([here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L5352)) is currently the same as the `order` set for water ([here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L911)). This causes the areas where they overlap to flicker between the two layers:

![screen shot 2015-12-07 at 12 12 31 pm](https://cloud.githubusercontent.com/assets/3371850/11633910/d0db162e-9cdb-11e5-9267-338e4b0176b2.png)

**Comment by nvkelso** [comment]
The flickering has been addressed in other Tangram commits. 

But the root bad ordering is still a problem in the scene file (causing the render to not be to spec), so keeping this issue open.
