### ISSUE TITLE
Sprite sheet region definition includes extra buffer

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#118]
We're hacking an extra pixel on the bottom and a couple on the right side to get around some masking / export issues now, but that's causing Tangram ES label text to icon collision to get confused (especially for townspots).

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/eraser-map/issues/62

**Comment by nvkelso** [comment]
Should be fixed in https://github.com/tangrams/eraser-map/commit/48acded90ccd1761f5a00c892434117b09d6af2e and https://github.com/tangrams/eraser-map/commit/8c5b1eaf0049d4cad05a60f47de9784e617511e5. Waiting to verify with a new Eraser Map build (soft verified in Tangram JS, though).

**Comment by matteblair** [comment]
Confirmed fixed!
