### ISSUE TITLE
Buildings should extrude into view (not pop)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#124]
We x-fade the building extrusion so it's less extreme at street-level zooms (which is very nice). But now the big buildings just POP into full extrusion at the mid-zooms. Instead it would be nice if they "grew" into their full height (very quickly in the same integer zoom) before slowly getting shorter.

**Comment by nvkelso** [comment]
@meetar Can you take a look, please?

**Comment by meetar** [comment]
I'll take the case 🔎
