### ISSUE TITLE
Water fills need to sort above golf courses

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#126]
http://tangrams.github.io/eraser-map/#16/39.6902/-75.7673

<img width="764" alt="screen shot 2015-12-23 at 09 45 55" src="https://cloud.githubusercontent.com/assets/853051/11981747/36e047e8-a95a-11e5-970c-7a9098650a19.png">

**Comment by nvkelso** [comment]
I suspect river lines are below water fills now (the reverse needs to be true, see Potomac River in Washington DC).

**Comment by sensescape** [comment]
<img width="725" alt="screen shot 2016-01-27 at 1 09 58 pm" src="https://cloud.githubusercontent.com/assets/466585/12628408/db2f24dc-c4f7-11e5-8451-c8f0355bc66c.png">

fixed
