### ISSUE TITLE
No city labels (townspot, name) on ES

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#127]
Below is a screenshot of the capital region of NH, which should have labels for Concord, Manchester, and Salem. Zooming in & out I couldn't find them:

![unnamed-1](https://cloud.githubusercontent.com/assets/853051/12084265/e8c26ab8-b265-11e5-9a6d-508bb3ce0ab7.png)

**config**
Manufacturer: samsung
Model: SAMSUNG-SM-G925A
Release: 5.1.1
Code name: REL
SDK: 22
Build number: master-598

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/eraser-map/issues/118

**Comment by bcamper** [comment]
I had restored these at some point by adjusting the label offsets, but it looks like these commits https://github.com/tangrams/eraser-map/commit/6ac67aac6bdf68cee2b788dd89d7c50840de89b0 and https://github.com/tangrams/eraser-map/commit/c89238172c4c027749d9d12bf6fec997606605fe again caused the text and icons to overlap (thus to collide, and the icons have higher priority so the text is hidden). (Note comment about spacing being set to "half icon size" in previous commit, which is no longer true... that's what kept them from overlapping.) This can be verified by setting `collide: false` on the text at the root of the `places` layer.

Looks like we can address by tightening the sprites re: #118, then adjusting these offsets back to ensure the text clears below the icon.

**Comment by bcamper** [comment]
Note: I upgraded this repo to use Tangram 0.5, which means that these place labels are also now missing from the web map (due to addition of sprite collision in tangram 0.5.0). However this matches the ES behavior so I believe it's best to keep things current and reflecting cross-platform behavior.

**Comment by nvkelso** [comment]
Sounds good, thanks. Consistency is (almost) always better!

**Comment by nvkelso** [comment]
Should be fixed in https://github.com/tangrams/eraser-map/commit/48acded90ccd1761f5a00c892434117b09d6af2e and https://github.com/tangrams/eraser-map/commit/8c5b1eaf0049d4cad05a60f47de9784e617511e5. Waiting to verify with a new Eraser Map build (soft verified in Tangram JS, though).

**Comment by bcamper** [comment]
:city_sunrise:

**Comment by nvkelso** [comment]
Verified on device.

**Comment by bcamper** [comment]
:iphone: :mag_right: :city_sunset:
