### ISSUE TITLE
Flickering blue fill for creek

### ISSUE THREAD

**Issue by souperneon** [tangrams/eraser-map#129]
![2016-01-04 7](https://cloud.githubusercontent.com/assets/6125224/12095087/77b69a36-b2da-11e5-9e1a-675cadf45f96.png)

**Comment by sensescape** [comment]
cannot reproduce, @souperneon can you provide more info?

**Comment by tallytalwar** [comment]
I think this was addressed here: https://github.com/tangrams/eraser-map/pull/123.

@souperneon can you please verify and close? Thanks

**Comment by souperneon** [comment]
I can test while driving this weekend and close
