### ISSUE TITLE
Adjust coastline lines per zoom

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#13]
- [x] Tiles have data
- [x] Functional style
- [ ] Styling polish

<img width="319" alt="screen shot 2015-09-16 at 4 18 54 pm" src="https://cloud.githubusercontent.com/assets/466585/9921080/e624fba4-5c8e-11e5-936b-b88a370b2be9.png">

**Comment by nvkelso** [comment]
We can adjust adjust it per water feature type (ocean, lake).

**Comment by sensescape** [comment]
done
