### ISSUE TITLE
New asset for routing arrow

### ISSUE THREAD

**Issue by souperneon** [tangrams/eraser-map#133]
Updated asset with circle around it

**Comment by sensescape** [comment]
Ok this has been updated. Had to make a slight adjustment on the circle size, it is slightly smaller, It was right on the edge of the sprite sheet. Let's see how this works.

**Comment by nvkelso** [comment]
In app, but it's distorted?

**Comment by nvkelso** [comment]
Size is looking good now in drive tests, and latest sprite sheet is PNG24 which should give us the semi-transparent white badge.

See also:
- https://github.com/tangrams/eraser-map/commit/48acded90ccd1761f5a00c892434117b09d6af2e

**Comment by nvkelso** [comment]
Verified on device!
