### ISSUE TITLE
Add text halos to street labels for routing

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#150]
Street text labels on top of the route line are hard to see (black on blue) at the default routing zoom. Zooming out from there, white halos are used. Let's continue those to the max zoom.

**Comment by sensescape** [comment]
done
![screenshot_2016-02-05-16-07-03](https://cloud.githubusercontent.com/assets/466585/12862690/a83ef82c-cc22-11e5-9f5a-1715e22f114e.png)
