### ISSUE TITLE
Coordinate UI icon colors with eraser-map app UI colors

### ISSUE THREAD

**Issue by matteblair** [tangrams/eraser-map#158]
Blue is the new green
![screenshot_20160223-142005](https://cloud.githubusercontent.com/assets/3371850/13265804/f709b7f2-da42-11e5-9f86-19b3b219954d.png)

**Comment by nvkelso** [comment]
Geraldine has started work on this, expected to land tomorrow.

**Comment by sensescape** [comment]
this is done

**Comment by nvkelso** [comment]
master-988
