### ISSUE TITLE
Buildings draw twice at some zooms

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#16]
- [x] Just do it

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1380-L1440

-I'd like buildings footprints to appear at z14 for those buildings that extrude at z15 (can't get the filters at building-early to do this)

**Comment by nvkelso** [comment]
@bcamper and @patriciogonzalezvivo for help optimizing the YAML filters.

**Comment by bcamper** [comment]
No problem. To clarify, is this the desired logic:
- at z14, a subset of buildings render as footprint
- at z15, that same subset from z14 is now extruded, and all remaining buildings are drawn as footprint
- at z16, all buildings are extruded

Is that right?

**Comment by bcamper** [comment]
Hm, looks like not all buildings are extruded until z17, but I still can't tell entirely what is supposed to happen, so please clarify :)

**Comment by sensescape** [comment]
z14 - Yes, at z14 as a transition to the buildings that will get extruded at z15, their footprints show.
z15 - bldg footprints with height: { min: 190 } get extruded, while all buildings footprints with  area: { min: 500 } show
z16 - footprints with area: { min: 100 } show and buildings with height: { min: 100 } get extruded

These filters are being used for extrusion:
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1973-L1978

Peter's building extrusion transition with the tilting of the z-axis is also working here, so that short buildings extrude but don't look too short. And if they're very short, they stay as building footprints. I think this transition looks good : )

I think the main thing here is that the buildings footprints may be drawing twice since there are 2 building layers: buildings_early and buildings
And Nathaniel said the footprints are drawing twice. I didn't know how to clean it up and have it only draw once without breaking the current look now, which is good.

**Comment by sensescape** [comment]
This is the building extrusion code from Peter:
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L757-L767

**Comment by nvkelso** [comment]
There’s duplication: the buildings that are extruded should be extruded,
but right now they also draw as **not** extruded first, then another pass
for extruded over them.

**Comment by bcamper** [comment]
Working on this here: https://github.com/tangrams/eraser-map/compare/simplify-buildings

**Comment by bcamper** [comment]
Addressed by PR #50.

**Comment by bcamper** [comment]
@nvkelso @sensescape moved this up to priority 2 because of performance concerns.

**Comment by bcamper** [comment]
#50 was merged so this should be done.
