### ISSUE TITLE
Landuse/buildings filter

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#17]
Started to test out styling buildings on various landuse types, starting with universities. Not drawing...

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1573-L1579

<img width="617" alt="screen shot 2015-09-17 at 2 31 26 pm" src="https://cloud.githubusercontent.com/assets/466585/9946625/4c320508-5d49-11e5-900f-7bffd80e8530.png">

**Comment by nvkelso** [comment]
You'll probably need to mod the shader to accept colors.

**Comment by nvkelso** [comment]
Dup of: https://github.com/tangrams/eraser-map/issues/26
