### ISSUE TITLE
Some airport runways are not drawing

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#18]
JFK, Heathrow and LaGuardia are not drawing runways, but SFO is drawing.
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L2736-L2744

<img width="211" alt="screen shot 2015-09-17 at 4 20 47 pm" src="https://cloud.githubusercontent.com/assets/466585/9948488/68875154-5d58-11e5-9d1c-3f94b7ac534e.png">
<img width="289" alt="screen shot 2015-09-17 at 4 20 51 pm" src="https://cloud.githubusercontent.com/assets/466585/9948490/68a1a612-5d58-11e5-9bc7-29375313136a.png">
<img width="259" alt="screen shot 2015-09-17 at 4 21 19 pm" src="https://cloud.githubusercontent.com/assets/466585/9948489/68a0dbe2-5d58-11e5-931a-06a7f57da40b.png">

**Comment by sensescape** [comment]
Style aprons:
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L2745-L2752

**Comment by nvkelso** [comment]
Fixed in: https://github.com/tangrams/eraser-map/commit/8a08f9d2b5e5dba8ac735ef126e7b6a2954e9de5
