### ISSUE TITLE
Add transit map options

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#189]
See https://github.com/mapzen/eraser-map/issues/710 and https://github.com/mapzen/eraser-map/issues/711 for transit map mode browsing, transit route selection, transit route preview / nav.

**Comment by nvkelso** [comment]
Suggest this can be configured via a new global:
- **`sdk_transit_overlay`** which defaults to `false` but can be set to `true`. Optionally we might support an `auto` value which would toggle it depending on variety of circumstances. 

There are several different factors that could impact `auto` including https://github.com/mapzen/eraser-map/issues/710 and https://github.com/mapzen/eraser-map/issues/711. But if the interface should allow someone to force it on or off.

**Comment by tallytalwar** [comment]
A basic state of `false` and `true` seems good to me. I am assuming you will be assigning this global to the `visible` property of the transit layer(s). 

The `auto` one could be interesting, how do you plan use it in the layers? It might need some more information to determine when to turn a transit layer `on`/`off`.

**Comment by nvkelso** [comment]
This was completed a few months ago.
