### ISSUE TITLE
Filters for building footprints and extrusions should extend to zoom 20

### ISSUE THREAD

**Issue by matteblair** [tangrams/eraser-map#200]
To support https://github.com/tangrams/bubble-wrap/pull/198, the filters here should be extended: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L2693-L2728

**Comment by matteblair** [comment]
@nvkelso: Varun or I could make educated guesses about what these should be. Is that worth doing or would you prefer to just write this yourself?

**Comment by nvkelso** [comment]
I’m not sure I follow. All footprints should be visible at zoom 17+, and
all buildings should be extruded at 18+. Please propose changes.

**Comment by matteblair** [comment]
In #198 we want to support a 'switch' that turns off building extrusions everywhere and instead shows only building footprints at all zooms. Currently, the filter on the 'footprints' layer makes all footprints stop at zoom 18. Consequently, when we turn off the 'extrude' layer there are no buildings at all past zoom 18. If we intend the style to support viewing up to zoom 20 then we should be able to show footprints to zoom 20 when extrusions are turned off.

**Comment by bcamper** [comment]
This should now be covered by changes in #198.
