### ISSUE TITLE
platforms are not transparent

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#207]
alpha not working anymore:
<img width="227" alt="screen shot 2016-10-20 at 5 43 05 pm" src="https://cloud.githubusercontent.com/assets/466585/19582851/c8b01df8-96ec-11e6-89c1-7307b38250e5.png">

https://github.com/tangrams/bubble-wrap/blob/sensescape/shields/bubble-wrap.yaml#L1602-L1604

**Comment by nvkelso** [comment]
This got fixed along the way (we think a Tangram regression that was fixed.)
