### ISSUE TITLE
Highway ramps should be distinct from thru roads

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#21]
This is around Dulles Airport outside of DC:

http://tangrams.github.io/eraser-map/#13/38.9585/-77.4284

<img width="456" alt="screen shot 2015-09-21 at 11 22 54" src="https://cloud.githubusercontent.com/assets/853051/10000828/522a88e2-6053-11e5-8669-b30f9c8454b8.png">

**Comment by sensescape** [comment]
Fixed the casing:
<img width="393" alt="screen shot 2015-09-28 at 12 13 35 pm" src="https://cloud.githubusercontent.com/assets/466585/10145846/6cf36676-65da-11e5-929e-1405629c9571.png">

**Comment by nvkelso** [comment]
nice!
