### ISSUE TITLE
Mobile version with less "interactive"

### ISSUE THREAD

**Issue by ecgreb** [tangrams/eraser-map#215]
Would it be possible to create a mobile version of the bubble wrap style with fewer layers marked `interactive`?

For example in Eraser Map we only want the following types of features to be interactive:

1. POIs with icons and labels displayed on the map
2. Search result pins placed by the app

## POIs

![poi](https://cloud.githubusercontent.com/assets/464123/20531704/8c3c0620-b0a5-11e6-814d-5a38613d7a07.png)

## Search Results

![search-result](https://cloud.githubusercontent.com/assets/464123/20531672/74d87d1a-b0a5-11e6-8fac-1cc59adedfdd.png)

Currently many more layers are marked interactive which is causing unexpected behavior when other features on the map are single tapped (buildings, roads, land features, etc).

It might also be nice if this behavior could be toggled using a global variable.

I'm happy to submit a set of changes (or keep them on a separate branch used only for the mobile SDKs and apps) but I could use some direction about which layers keep as interactive to produce the desired behavior.

Original Eraser Map issue is here https://github.com/mapzen/eraser-map/issues/775.

**Comment by nvkelso** [comment]
@tallytalwar You mentioned that you made some changes for this in a branch, is it [varun/testing-interactive-icons](https://github.com/tangrams/bubble-wrap/tree/varun/testing-interactive-icons)?

**Comment by tallytalwar** [comment]
@nvkelso yes. I did a quick removal of `interactive` draw rules for everything other than icons or points style.

Also `interactive` is not a style parameter. So removed all references of it from any user defined styles.

**Comment by ecgreb** [comment]
@tallytalwar nice work your branch does seem to produce the desired behavior in the app. If these changes are ok on web too then might not be a need for a separate mobile version of the stylesheet.

**Comment by nvkelso** [comment]
Completed in https://github.com/tangrams/bubble-wrap/pull/224.
