### ISSUE TITLE
Style search result pins

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#23]
- [x] Data in app
- [x] Functional art
- [x] Delivered by Ekta
- [x] Integrate into sprite sheet and scene file
- [x] Functional styling
- [ ] Polish art & styling

https://github.com/mapzen/eraser-map/blob/master/app/src/main/assets/scene.yaml#L52-L73:D

**Comment by nvkelso** [comment]
Assigning to Ekta to provide artwork asset to Geraldine.

**Comment by souperneon** [comment]
@nvkelso @sensescape I sent these over email the other day. There are png's for all android sizes and an .ai files with raw assets.
Green pin the active/selected pin and dark grey is inactive

**Comment by nvkelso** [comment]
@ecgreb What source name is used for search active versus inactive? Both assets are packed, but we're only generically styling `search` with the green pins in the scene file now.

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/eraser-map/issues/133

**Comment by sensescape** [comment]
done
