### ISSUE TITLE
Add zip distribution on next release

### ISSUE THREAD

**Issue by bcamper** [tangrams/eraser-map#234]
With recent additions like new fonts, Bubble Wrap is now loading several more files. We can improve client-side load efficiency by offering a zip bundle version of the style. This needn't be exclusive of the existing `bubble-wrap.yaml` distribution, we can simply upload both to mapzen.com.

**Comment by nvkelso** [comment]
This required some changes in the Bundler, merged in https://github.com/tangrams/bundler/pull/5.

Other work is tracked in https://github.com/mapzen/carto-s3-bucket/issues/6.

**Comment by nvkelso** [comment]
This work was completed last release.
