### ISSUE TITLE
Style buildings within landuse university, park and other green areas

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#26]
- [x] Tiles has the data
- [x] Functional styling in scene file
- [x] Polish styling

<img width="367" alt="screen shot 2015-09-23 at 10 47 35 am" src="https://cloud.githubusercontent.com/assets/466585/10053421/c9f46832-61e0-11e5-9604-d64e3547953b.png">

**Comment by sensescape** [comment]
Also within the shader

**Comment by sensescape** [comment]
Need help with building shader to make it easier to set colors for building sides/facades
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L775-L804

**Comment by sensescape** [comment]
<img width="404" alt="screen shot 2015-09-29 at 11 44 16 am" src="https://cloud.githubusercontent.com/assets/466585/10174592/72024996-669f-11e5-9257-57feb8c302dd.png">

**Comment by patriciogonzalezvivo** [comment]
a more comprehensive way of writing that is:

``` glsl
                    if ( dot(vec3(0.,0.,1.),normal) == 1.0 ) {
                        // is a roof
                        color.rgb = vec3(0.,0.,1.);
                    } else {
                        // is a wall
                        color.rgb = vec3(1.0,0.,0.);
                    }
```

At http://tangrams.github.io/tangram-play/?style=https://raw.githubusercontent.com/tangrams/eraser-map/gh-pages/eraser-map.yaml&lines=783-786#16.42333333333333/40.76963/-73.98839

![screen shot 2015-09-29 at 2 53 27 pm](https://cloud.githubusercontent.com/assets/346914/10174878/facf5a88-66b9-11e5-8860-029933a599ff.png)

**Comment by sensescape** [comment]
fixed!

<img width="393" alt="screen shot 2015-09-29 at 3 58 16 pm" src="https://cloud.githubusercontent.com/assets/466585/10180565/149991be-66c3-11e5-8def-a18f2d188a0b.png">

**Comment by sensescape** [comment]
with new roof colors:
<img width="258" alt="screen shot 2015-09-30 at 3 57 34 pm" src="https://cloud.githubusercontent.com/assets/466585/10208973/17009794-678c-11e5-9d45-c340b6083f96.png">
<img width="209" alt="screen shot 2015-09-30 at 3 58 34 pm" src="https://cloud.githubusercontent.com/assets/466585/10208976/21577a78-678c-11e5-8314-b5a9eb21c633.png">

**Comment by nvkelso** [comment]
Nice! Can the not-extruded footprints get the same roof color?
