### ISSUE TITLE
bubble-wrap-shields-usa@2x.png has extra area

### ISSUE THREAD

**Issue by matteblair** [tangrams/eraser-map#268]
![screen shot 2018-03-22 at 12 34 44 pm](https://user-images.githubusercontent.com/3371850/37784105-6f5495b2-2dcd-11e8-92c7-beb1cecf1dbd.png)

Let's keep it trimmed to save HTTP and rendering resources!

**Comment by nvkelso** [comment]
No longer an issue:

![bubble-wrap-shields-usa 2x](https://user-images.githubusercontent.com/853051/49420724-b49e2c80-f741-11e8-8ebb-b272558eaac9.png)
