### ISSUE TITLE
Style roads in landuse:residential within parks

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#28]
- [ ] Plan of action

Not sure what to do here, residential roads within parks, my colors aren't drawing:
<img width="1135" alt="screen shot 2015-09-23 at 12 01 08 pm" src="https://cloud.githubusercontent.com/assets/466585/10055440/25ec7760-61eb-11e5-8dff-94775ca64bf3.png">

**Comment by nvkelso** [comment]
@zerebubuth another `landuse_kind` server side sorting problem?
