### ISSUE TITLE
Fix highway links transition

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#3]
- [x] Tiles have functional data
- [x] Style is functional
- [ ] Style polish

<img width="113" alt="screen shot 2015-09-11 at 4 19 16 pm" src="https://cloud.githubusercontent.com/assets/466585/9825366/ec13e86e-58a0-11e5-8cbe-67bab723a107.png">

**Comment by nvkelso** [comment]
This is working now.
