### ISSUE TITLE
Mix of landuse kind wood and park in Prospect Park Brooklyn

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#33]
Not sure what to do here:
<img width="784" alt="screen shot 2015-09-23 at 3 56 36 pm" src="https://cloud.githubusercontent.com/assets/466585/10061239/ef4f3faa-620b-11e5-85c5-e3a541a7491b.png">
<img width="462" alt="screen shot 2015-09-23 at 3 58 15 pm" src="https://cloud.githubusercontent.com/assets/466585/10061240/ef67bc38-620b-11e5-98e3-092bc6295331.png">

**Comment by nvkelso** [comment]
Add `wood` to the `park` layer’s filter.

**Comment by sensescape** [comment]
ok, added

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1705

<img width="475" alt="screen shot 2015-09-23 at 4 44 31 pm" src="https://cloud.githubusercontent.com/assets/466585/10061985/a28e7968-6212-11e5-914b-49ada300af8b.png">
