### ISSUE TITLE
Redesign steps styling (work around shader bug)

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#35]
- [ ] Plan of action?

<img width="216" alt="screen shot 2015-09-23 at 4 48 01 pm" src="https://cloud.githubusercontent.com/assets/466585/10062018/e36831d6-6212-11e5-99a1-f09ce9592493.png">

**Comment by sensescape** [comment]
<img width="434" alt="screen shot 2015-09-23 at 4 49 17 pm" src="https://cloud.githubusercontent.com/assets/466585/10062032/0e9e95f2-6213-11e5-9729-b14ad5c4a5f8.png">

**Comment by sensescape** [comment]
Fort Greene Park

**Comment by nvkelso** [comment]
Very noticeable, but LOE to fix is high.

**Comment by nvkelso** [comment]
@bcamper do you think the Tangram piece of this can be fixed in a couple weeks? Or should we pull these / restyle them for initial release?

**Comment by bcamper** [comment]
@patriciogonzalezvivo and I started looking but it's blocked by some other line work (for level-of-detail adjustment to avoid high polygon counts) first. We may be able to address in JS by then, but probably not ES, so let's defer and plan to revisit soon (will keep working on it on JS side).

**Comment by sensescape** [comment]
this has been cleaned up, it will still stretch and contract because of texcoords
