### ISSUE TITLE
Style airports at high and low zooms

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#37]
- [x] Functional data in tiles
- [x] Polish data in tiles
- [x] Functional styling
- [x] Polish styling

<img width="489" alt="screen shot 2015-09-23 at 4 51 35 pm" src="https://cloud.githubusercontent.com/assets/466585/10062065/783ed260-6213-11e5-85d4-3e4ec43c728b.png">
<img width="114" alt="screen shot 2015-09-23 at 4 51 52 pm" src="https://cloud.githubusercontent.com/assets/466585/10062066/7868b1fc-6213-11e5-8b26-a3a5410b06b9.png">

**Comment by sensescape** [comment]
Recolored taxiways and runway outlines

<img width="105" alt="screen shot 2015-09-24 at 4 09 13 pm" src="https://cloud.githubusercontent.com/assets/466585/10089304/cd6c607c-62d6-11e5-8509-58d416718747.png">
<img width="782" alt="screen shot 2015-09-24 at 4 09 34 pm" src="https://cloud.githubusercontent.com/assets/466585/10089305/d2ee274c-62d6-11e5-8b22-ff383ed7fbbd.png">

**Comment by nvkelso** [comment]
Could use more polish, but working pretty good now :)

Looks like we're missing runways from tiles earlier than zoom 11. Those are bucketed with minor_road, and just the runways should be coming in at zoom 9. That requires a query change: https://github.com/mapzen/vector-datasource/issues/278.

**Comment by nvkelso** [comment]
The airport icons needed to be visible earlier, I've fixed that in Skin & Bones so let's rebase.

**Comment by nvkelso** [comment]
Looks different and better now.
