### ISSUE TITLE
Style roads/paths in landuse nature reserve

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#38]
<img width="741" alt="screen shot 2015-09-23 at 5 11 09 pm" src="https://cloud.githubusercontent.com/assets/466585/10062315/3c7e11b6-6216-11e5-8a46-d835c52d76df.png">

http://localhost:8000/#16/41.8698/12.5045

**Comment by sensescape** [comment]
<img width="762" alt="screen shot 2015-09-24 at 11 37 48 am" src="https://cloud.githubusercontent.com/assets/466585/10082872/b9cdb258-62b0-11e5-911c-8d54415a0477.png">

**Comment by nvkelso** [comment]
Can we improve the visual distinction between paths and water lines?

**Comment by sensescape** [comment]
Yes, definitely. Those colors are too close to each other, can't distinguish.
