### ISSUE TITLE
BLOCKED: Ferry lines show at z7-8 then disappear

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#39]
- [x] Tiles have functional data (prototype with Natural Earth only)
- [ ] Tiles have all data (needed OSM additions)
- [x] Functional style
- [ ] Styling polish

http://localhost:8000/#7/40.181/2.049

**Comment by nvkelso** [comment]
Blocked by missing data in tiles: https://github.com/mapzen/vector-datasource/issues/187

**Comment by nvkelso** [comment]
Data isn't landing for another couple weeks, sorry.

**Comment by sensescape** [comment]
this is done
