### ISSUE TITLE
z5 city labels are sparse

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#41]
- [x] Tiles have data
- [x] Functional style
- [x] Styling polish

<img width="626" alt="screen shot 2015-09-28 at 3 46 01 pm" src="https://cloud.githubusercontent.com/assets/466585/10151020/3e644e42-65f8-11e5-97ca-67047e701ac4.png">

**Comment by nvkelso** [comment]
This looks better in Skin and Bones, let's rebase against that.

**Comment by nvkelso** [comment]
This was rebased.
