### ISSUE TITLE
Fix neighborhood labels

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#43]
- [x] Functional data in tiles
- [x] Polish data in tiles
- [x] Functional styling
- [x] Polish styling

Label content need improvement
<img width="304" alt="screen shot 2015-09-28 at 4 24 45 pm" src="https://cloud.githubusercontent.com/assets/466585/10151553/9bb07922-65fd-11e5-8e79-451ea7c6fcdf.png">

**Comment by sensescape** [comment]
<img width="295" alt="screen shot 2015-09-28 at 4 30 33 pm" src="https://cloud.githubusercontent.com/assets/466585/10151622/45cdc2e8-65fe-11e5-89ff-bca2f17c4019.png">

**Comment by nvkelso** [comment]
Blocked on: https://github.com/mapzen/vector-datasource/issues/147

**Comment by nvkelso** [comment]
This data is in dev tiles now, about to go to prod.
