### ISSUE TITLE
Add more space between the dots in new dot interpolation shader

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#46]
The dots are so close together, it's making the color more intense. Could we add more space to the dots. Or match this:
<img width="679" alt="screen shot 2015-09-29 at 11 32 02 am" src="https://cloud.githubusercontent.com/assets/466585/10174334/2cff962e-669e-11e5-8de8-e2063c065d31.png">
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L719-L725

Here's how it looks with the new dot interpolation, with more closely packed dots:
<img width="679" alt="screen shot 2015-09-29 at 11 31 32 am" src="https://cloud.githubusercontent.com/assets/466585/10174359/50c22acc-669e-11e5-9b31-268aec3c2072.png">
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L719-L725

**Comment by patriciogonzalezvivo** [comment]
Hello Geraldine, to space the dots you need to scale the space up (first argument of `TileDots()`) and reduce the radius of the dots (second argument of `TileDots()`).
You can try it your self here http://tangrams.github.io/tangram-play/?style=https://raw.githubusercontent.com/tangrams/eraser-map/gh-pages/eraser-map.yaml&lines=725

![screen shot 2015-09-29 at 2 47 55 pm](https://cloud.githubusercontent.com/assets/346914/10174759/72b26258-66b9-11e5-89aa-c7a494ba9914.png)
![screen shot 2015-09-29 at 2 47 41 pm](https://cloud.githubusercontent.com/assets/346914/10174760/72b3aef6-66b9-11e5-9f8c-c4964e20e377.png)
