### ISSUE TITLE
Fix bridge casings

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#5]
<img width="253" alt="screen shot 2015-09-11 at 4 22 44 pm" src="https://cloud.githubusercontent.com/assets/466585/9825453/62b0e1f2-58a1-11e5-9956-fbb5909c6f16.png">

**Comment by sensescape** [comment]
Current state of golden gate bridge, looks like a lot of layering of lines, not sure what's going on here:

<img width="386" alt="screen shot 2015-09-23 at 3 14 48 pm" src="https://cloud.githubusercontent.com/assets/466585/10060468/f4e4c1f2-6205-11e5-9147-ff0e90033c22.png">

**Comment by sensescape** [comment]
<img width="256" alt="screen shot 2015-09-23 at 3 15 59 pm" src="https://cloud.githubusercontent.com/assets/466585/10060480/05561e28-6206-11e5-96a6-c3a6c0728d84.png">

**Comment by nvkelso** [comment]
This is because there is a bridge landuse polygon with 4 lines on top of it: 2 road lines (inbound, outbound), and 2 pedestrian paths on the outside (inbound, outbound).

https://www.openstreetmap.org/edit#map=19/37.81312/-122.47747

**Comment by nvkelso** [comment]
Here's an example tile:
- http://vector.mapzen.com/osm/all/19/83773/202581.topojson?api_key=vector-tiles-HqUVidw

It looks like the bridge is getting an `attraction` tag right now instead of the `bridge` tag, that's probably a bug in the tiles code (https://github.com/mapzen/vector-datasource/issues/238).

**Comment by nvkelso** [comment]
Suggest moving the default path sort order **below** the highways. That should probably be done upstream with https://github.com/mapzen/vector-datasource/issues/239.

**Comment by nvkelso** [comment]
Closing this in favor of the vector-datasource fix.
