### ISSUE TITLE
Create mobile branch of Tangram scene assets for use in android builds

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#54]

**Comment by bcamper** [comment]
Are there any known divergences between JS and ES that necessitate this currently? Obviously the goal is parity so the scene file is interchangeable, but pragmatically understand that we may need some small divergence in initial release if we can't get there.

**Comment by matteblair** [comment]
The issue isn't differences in the scene file per se, rather that the
eraser map style repo has a lot of things that we don't want to bundle in
an apk (js files, readme, etc)

The idea here is to make a repo/branch that has just the scene file and
assets for Android to pull in as a submodule.

**Comment by bcamper** [comment]
Is that significantly better than a simple makefile step that pulls them in over the network? They can still be pegged to specific version/commit. I think in terms of what we need vs. don't, I think we could have a simple pattern like "the `eraser-map.yaml` file + everything in a `resources/` dir". Anyway either will work, just different maintenance between them.

**Comment by nvkelso** [comment]
If there aren't any substantial changes between WebGL styling and ES styling, then there's no need for another branch and https://github.com/mapzen/eraser-map/issues/67 can be pursued alone. Ekta's been consistent in her feedback that they will diverge eventually. So seems like fix https://github.com/mapzen/eraser-map/issues/67 and hold off on this issue until it's a problem.

**Comment by bcamper** [comment]
I would really like to try to keep them consistent... so let's assume they will be to start (platform compatibility allowing), and we'll address aesthetic or usability concerns later.

**Comment by nvkelso** [comment]
We've done away with the android branch!
