### ISSUE TITLE
BLOCKED: Add line breaks to POI labels

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#55]
This would significantly improve the quality of our labels. @bcamper @nvkelso 

<img width="451" alt="screen shot 2015-10-23 at 11 37 02 am" src="https://cloud.githubusercontent.com/assets/466585/10701809/8f22bd92-797a-11e5-978c-a5063a8f4c4d.png">

**Comment by bcamper** [comment]
Yes I know :)  Plan to look at this soon on the Tangram side.

**Comment by nvkelso** [comment]
Is there a Tangram issue we can block this styling issue on, please?

**Comment by bcamper** [comment]
In trello (may end up migrating them to github but not immediately): https://trello.com/c/0dvqDBQR/444-multi-line-labels

**Comment by nvkelso** [comment]
This is in Tangram v0.4 on by default. 

Let's leave this open to refine the 15 char width.

**Comment by nvkelso** [comment]
Nothing more to do here except in one-off situations.
