### ISSUE TITLE
Fix borders

### ISSUE THREAD

**Issue by sensescape** [tangrams/eraser-map#6]
- [x] Data in dev tiles
- [x] Data in prod tiles
- [x] Functional styling in scene file
- [ ] Polish styling

<img width="409" alt="screen shot 2015-09-11 at 4 32 34 pm" src="https://cloud.githubusercontent.com/assets/466585/9825657/c257d358-58a2-11e5-9399-3ff7bc3facc4.png">

**Comment by nvkelso** [comment]
Blocked by: https://github.com/mapzen/vector-datasource/issues/210

**Comment by nvkelso** [comment]
This was done a while ago.
