### ISSUE TITLE
Remove uses of ES6 String.includes()

### ISSUE THREAD

**Issue by bcamper** [tangrams/eraser-map#60]
There are several places where we are using the `String.includes()` method:

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L2683

This is actually a fairly recent addition (to ES6), and isn't guaranteed to be supported on all browsers (and in this case we found out because it wasn't supported in the JS parser we are using for Tangram ES). Instead, we should stick to ES5-flavored JS, as it will be consistently available on all platforms supported by Tangram. 

In this case, `includes()` is really just a convenience function, and can be easily written with the older `indexOf()` instead, e.g.:

Instead of:
`filter: function() { return feature.name && feature.name.includes("Park") && !feature.name.includes("National Park")}`

Use this:
`filter: function() { return feature.name && feature.name.indexOf("Park") > -1 && !feature.name.indexOf("National Park") > -1}`

**Comment by nvkelso** [comment]
Change will be made in Skin & Bones and then rebased into Refill and Eraser Maps.

**Comment by tallytalwar** [comment]
9b66dc7e63b26e836348911c99799c40d5ce808f fixes this in android branch.
