### ISSUE TITLE
Order definition for train and subway

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/eraser-map#61]
This could be something on the es side. But creating an issue for reference.

![screenshot_2015-10-28-08-23-01](https://cloud.githubusercontent.com/assets/360641/10788427/c77e79fc-7d4d-11e5-8583-ac1af44e4744.png)

![screenshot_2015-10-28-11-05-51](https://cloud.githubusercontent.com/assets/360641/10792720/4a3988da-7d64-11e5-8cc8-2990298e5c28.png)

**Comment by nvkelso** [comment]
Is this about the rail lines being rendered under the water and park polygons? 

Or the strange rendering artifacts on the first image (Miltiades Ave)?

**Comment by tallytalwar** [comment]
Yeah, there is some order issue, where either some landuse features are not definiting an order, or order being calculated for rail/lightrail/subway/landuse is wrong.

Example: https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L3317, landuse features do not define an order.

**Comment by tallytalwar** [comment]
If we ignore any feature which does not define an order, this is the result we get for the second image:

![screen shot 2015-10-28 at 11 43 35 am](https://cloud.githubusercontent.com/assets/360641/10793922/4524573a-7d69-11e5-92e8-a34b90f6b010.png)

**Comment by tallytalwar** [comment]
It seems the discrepancy between web and es, is coming from use of sort-key for subways, [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1009). And it looks like sort-key is not defined for transit/subways in the tiles.

```
Properties: {
 kind: "subway",
 network: "NYC Subway",
 colour: "#ee352e",
 route_name: "NYCS - 1 Train",
 operator: "Metropolitan Transportation Authority",
 ref: "1",
 id: -364630,
 osm_relation: true
}
```

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/353

**Comment by nvkelso** [comment]
I'm confused. Are you saying the `landuse` area is the feature missing `sort_key`, not the transit layer's rail feature?

**Comment by tallytalwar** [comment]
Nopes, ignore the initial investigation commit, `sort_key` is missing on the transit layer.

**Comment by tallytalwar** [comment]
So with recent changes to es, any feature not defining an `order`, `color` or `width` (defined `width` being greater than 0) will be ignored.

In this case, since transit features do not define `sort_key` and hence have a `NAN` order evaluated (based on the current order evaluation in the style sheet, [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1009)), will be ignored and not drawn.

Once we have `sort_keys` in our tile data for transit features, this issue should automatically be resolved.

**Comment by nvkelso** [comment]
Shouldn't it default to 0 when data not provided (rather than not draw)?

**Comment by tallytalwar** [comment]
Defaulting to 0, could result in features lying at the same z depth and hence could result in z-fighting for those features.

However, we can provide debug/edit mode drawing for such features, with an error color.

**Comment by matteblair** [comment]
More importantly, if we fall back to any default "order" value then elements will be layered according to the order of styles in the scene, which cannot be guaranteed to be consistent (even among browsers!). 

In other words, a default order would mislead people into thinking that their scene is correct when it really only looks a certain why by pure chance.

**Comment by nvkelso** [comment]
- Some landuse features are missing their data property: https://github.com/mapzen/vector-datasource/issues/364
- Style should set default: order: function() { return feature.sort_key || 1; }
- Larger Tangram policy question can be dealt with later.
