### ISSUE TITLE
Sprite atlas needs to be smaller than 2048 x 2048

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#62]
Else it won't work on older phones.

Update the Illustrator export script so it packs tighter (but not as tight as before).

**Comment by nvkelso** [comment]
Should be fixed in https://github.com/tangrams/eraser-map/commit/48acded90ccd1761f5a00c892434117b09d6af2e and https://github.com/tangrams/eraser-map/commit/8c5b1eaf0049d4cad05a60f47de9784e617511e5. Waiting to verify with a new Eraser Map build (soft verified in Tangram JS, though).

/cc @blair1618

**Comment by matteblair** [comment]
Looks great to me!
