### ISSUE TITLE
Building grid texture not visible on certain phones

### ISSUE THREAD

**Issue by matteblair** [tangrams/eraser-map#65]
Extruded buildings should have a grid texture sampled from `building-grid.gif`:
![screen shot 2015-10-29 at 6 28 06 pm](https://cloud.githubusercontent.com/assets/3371850/10833776/e3191d0c-7e6a-11e5-9209-4ca407384568.png)

This works as expected on desktop, iOS, and most Android devices. However, on the Moto X (2014) and the Galaxy S5, the grid is not visible:
![screenshot_2015-10-29-18-23-16](https://cloud.githubusercontent.com/assets/3371850/10833802/10b80a02-7e6b-11e5-9aa6-e893a46428f5.png)

No GL errors are reported and driver capabilities don't seem to be correlated to the issue.

**Comment by tallytalwar** [comment]
You already know this, but for documentation, I did see the building grid texture on my S5 this morning.

**Comment by nvkelso** [comment]
@blair1618 Is there a styling ask here or is this a Tangram bug?

**Comment by tallytalwar** [comment]
Most likely this is on the tangram side, but as of now we do not know why certain phones including s5 are not showing building grid texture.

**Comment by blair1618** [comment]
@tallytalwar @nvkelso It's actually not anything we can solve within tangram - it's an issue with the custom shaders in the eraser-map scene file and the limitations of certain devices. I'm pretty confident that if you loaded the WebGL version of eraser-map on those devices you would see similar issues.

**Comment by tallytalwar** [comment]
@blair1618 I don't think we can guarantee that WebGL version on these devices would show similar issues. Possible browser masks certain issues. 

Example, previously the dots style issue (now fixed) was not working on S5 tangram-es, but was working in the web renderer on S5 chrome.

**Comment by tallytalwar** [comment]
Update on this:
- Still broken on S5 (5.0) and MotoX (5.1)
- Works on S5 (4.4).
- Does not work with another test 128x128 png texture image. So not specific to a gif texture. 
- Seems to be an issue with usage of `v_texcoords` in global injected functions. (material block specifically). We saw something similar with usage of `TileCoords` method which was causing issues with rendering of `dots` styles on certain devices.
- Attaching the test png texture here.
  ![testtex](https://cloud.githubusercontent.com/assets/360641/11007681/8e01a2e6-8499-11e5-8a0a-b922454769ca.png)
- Correct tangram-es render with the above texture:
  ![buildingtex_osx](https://cloud.githubusercontent.com/assets/360641/11007760/2727ca68-849a-11e5-948d-855a5516589b.png)
- tangram-es render on S5 (5.0) device:
  ![buildingtex_android](https://cloud.githubusercontent.com/assets/360641/11007765/2df4aa28-849a-11e5-9539-a819538d4d7c.png)
