### ISSUE TITLE
Style Route Icon

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/eraser-map#66]
https://github.com/tangrams/eraser-map/blob/android/eraser-map.yaml#L764-L787

Currently a route icon layer is missing all together, I am going to add one as a placeholder in the android branch, for it to be used in eraser-map app code.

**Comment by nvkelso** [comment]
Please add it in the main branch, too, so there are less merge conflicts later. (Web map will need this.)

**Comment by tallytalwar** [comment]
Cool, will do and rebase android branch. Thanks

**Comment by nvkelso** [comment]
This is a duplicate of: https://github.com/tangrams/eraser-map/issues/64.
