### ISSUE TITLE
Need to bundle font

### ISSUE THREAD

**Issue by bcamper** [tangrams/eraser-map#75]
On ES, labels right now are displaying with a default Android font because Helvetica isn't available. We need to bundle a font with the scene/app. We may not be able to use Helvetica for licensing reasons, so we need to find an appropriate free alternative, such as Arial.

**Comment by bcamper** [comment]
cc @sensescape @nvkelso

**Comment by tallytalwar** [comment]
https://github.com/tangrams/tangram-es/pull/387, uses aliases defined in android's font.xml. 
`helvetica` gets mapped to `sans-serif` which uses `Roboto` ttf files.

```
     <family name="sans-serif">
        <font weight="100" style="normal">Roboto-Thin.ttf</font>
        <font weight="100" style="italic">Roboto-ThinItalic.ttf</font>
        <font weight="300" style="normal">Roboto-Light.ttf</font>
        <font weight="300" style="italic">Roboto-LightItalic.ttf</font>
        <font weight="400" style="normal">Roboto-Regular.ttf</font>
        <font weight="400" style="italic">Roboto-Italic.ttf</font>
        <font weight="500" style="normal">Roboto-Medium.ttf</font>
        <font weight="500" style="italic">Roboto-MediumItalic.ttf</font>
        <font weight="900" style="normal">Roboto-Black.ttf</font>
        <font weight="900" style="italic">Roboto-BlackItalic.ttf</font>
        <font weight="700" style="normal">Roboto-Bold.ttf</font>
        <font weight="700" style="italic">Roboto-BoldItalic.ttf</font>
    </family>

    <!-- Note that aliases must come after the fonts they reference. -->
    <alias name="sans-serif-thin" to="sans-serif" weight="100" />
    <alias name="sans-serif-light" to="sans-serif" weight="300" />
    <alias name="sans-serif-medium" to="sans-serif" weight="500" />
    <alias name="sans-serif-black" to="sans-serif" weight="900" />
    <alias name="arial" to="sans-serif" />
    <alias name="helvetica" to="sans-serif" />
    <alias name="tahoma" to="sans-serif" />
    <alias name="verdana" to="sans-serif" />
```

**Comment by bcamper** [comment]
Oh I see. So it's good to support the aliases. But for styling quality, we want the real font, not the generic sans serif. So it looks like we still need to bundle something (though probably not Helvetica due to licensing).

**Comment by tallytalwar** [comment]
Yup. I agree sans-serif will not give desired styling quality.

**Comment by nvkelso** [comment]
I think this does it on the scene file side: 733ec72a734620eb1cc19962b9b71aacab7c0c51.

@tallytalwar and @blair1618 to confirm and embed latest scene file into Android app.

**Comment by matteblair** [comment]
@nvkelso See https://github.com/tangrams/eraser-map/pull/111/files, we need the actual files alongside the scene file (like we do with images). I'll rebase my pull request to use the anchor you've created.

**Comment by matteblair** [comment]
Resolved by https://github.com/tangrams/eraser-map/pull/111
