### ISSUE TITLE
Stroke the water boundaries geoms, not the water fills geoms

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#85]
We added explicate water line geoms marked with `boundary=yes` attributes a few tile versions ago to solve for this type of thing. This issue covers adopting the new feature sourcing to avoid the water edge stroke in the middle of the water feature (should only be on the shoreline).

12/38.0799/-121.6636

<img width="583" alt="screen shot 2015-11-11 at 16 27 52" src="https://cloud.githubusercontent.com/assets/853051/11107287/4a552c6a-8891-11e5-877e-af380808d6d1.png">

**Comment by sensescape** [comment]
done
