### ISSUE TITLE
Move POI image to root dir (not images dir)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#9]

**Comment by nvkelso** [comment]
This was done.

**Comment by tallytalwar** [comment]
@nvkelso We have a PR on tangram-es, https://github.com/tangrams/tangram-es/pull/297, which will allow us to have resources relative to the scene file.

Once we have that merged we will have to revert this change.

**Comment by tallytalwar** [comment]
https://github.com/tangrams/tangram-es/pull/297 got merged to master. Tangram-es will require resources to be relative to the scene yaml.

**Comment by nvkelso** [comment]
Will do in: https://github.com/tangrams/eraser-map/issues/34. The image file has changed since then, so the commit shouldn't be reverted.
