### ISSUE TITLE
[FIELDTEST] Road labels are too small while browsing the map

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#95]
These are too small overall still. They feel smallish but okay in the web browser, but they aren't legible on mobile device.
- [x] Basic improvements
- [ ] Polish improvements

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/eraser-map/issues/96

**Comment by nvkelso** [comment]
This is looking much better in master-569!

**Comment by nvkelso** [comment]
Geraldine landed fixes for these, time for another drive test.

**Comment by sensescape** [comment]
done
