### ISSUE TITLE
[FIELDTEST] Road labels are far too small during navigation

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#96]
During navigation I mount the phone farther away than I hold it, so the somewhat small road labels we have now become too tiny to read during the navigation experience.
- [x] Basic improvements
- [ ] Polish improvements

**Comment by nvkelso** [comment]
Looking much better in master-569!

**Comment by nvkelso** [comment]
After a week away, using master-598, these are still a smidgen too small.

**Comment by nvkelso** [comment]
Geraldine landed fixes for these, time for another drive test.

**Comment by sensescape** [comment]
done
