### ISSUE TITLE
Define priorities for pois

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/eraser-map#99]
There is no collision for point icons on JS side, and hence this is not visible on JS.
On ES, since no priority is defined for pois, these get assigned default (highest int value) which basically means the pois will get occluded by any higher priority label and hence do not show up. Which is what is happening at present in eraser-map (higher zoom level).

Refer:
https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L3978

**Comment by nvkelso** [comment]
Aha! That explains the difference between these two drive test images:

Expected (WebGL):

![img_7730-1](https://cloud.githubusercontent.com/assets/853051/11492809/bfed8368-97a6-11e5-8ae5-8953eb8bcd8a.PNG)

Observed (ES):

![screenshot_2015-11-29-19-04-17](https://cloud.githubusercontent.com/assets/853051/11492819/cfd9da2e-97a6-11e5-9050-f7c25def1830.png)

**Comment by nvkelso** [comment]
@tallytalwar Does this screenshot from Eraser Map show the same problem or a different problem? I see POI text names but not the POI icon parts of the labels. This is in Eureka California along [Broadway](https://www.openstreetmap.org/#map=17/40.78167/-124.18578). 

![screenshot_2015-11-27-15-54-28](https://cloud.githubusercontent.com/assets/853051/11493932/5c31e7f4-97b2-11e5-9311-2b7a09e06c22.png)

**Comment by tallytalwar** [comment]
Thanks for the comparison screen shots.

Yes, pois not having priorities and labels having priorities, makes the colliding label<->poi pair pick the label and not draw the poi.

**Comment by tallytalwar** [comment]
It would also make more sense to provide priorities for all labels and icons. Will definitely make the label/icon collision more consistent.

**Comment by nvkelso** [comment]
cc @bcamper Good example of needing a single "labels" symbolizer with text and icon parts.

**Comment by bcamper** [comment]
Yep :)

**Comment by nvkelso** [comment]
Should be mostly fixed in: 83e9ba7f98984cc523fe816565ed248957b174a8

**Comment by nvkelso** [comment]
The icons show up now instead of the text (good).

Further fixing is already tracked by https://github.com/tangrams/eraser-map/issues/118 (cropping sprites in sprite sheet) and https://github.com/tangrams/tangram-es/pull/429 (allowing stops for text offsets).
